# Generated by Django 3.2.5 on 2022-08-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('IN-PROGRESS', 'IN-PROGRESS'), ('ENDED', 'ENDED')], default='NEW', max_length=20),
        ),
    ]
