# Generated by Django 3.2.5 on 2022-08-09 09:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0002_alter_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='uid',
            field=models.UUIDField(default=uuid.uuid1, editable=False),
        ),
    ]
