# Generated by Django 3.2.5 on 2022-08-09 09:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0003_game_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='uid',
            field=models.UUIDField(blank=True, default=uuid.uuid1, editable=False, null=True),
        ),
    ]
