# Generated by Django 3.2.5 on 2022-08-09 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0005_auto_20220809_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='ttt.player'),
        ),
    ]
