# Generated by Django 3.2.5 on 2022-08-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0006_game_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='status',
            field=models.CharField(choices=[('BLANK', 'BLANK'), ('MARKED', 'MARKED')], default='blank', max_length=20),
        ),
    ]
