# Generated by Django 3.2.5 on 2022-08-09 16:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0008_alter_cell_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='uid',
            new_name='player_1_uid',
        ),
        migrations.AddField(
            model_name='game',
            name='player_2_uid',
            field=models.UUIDField(blank=True, default=uuid.uuid1, editable=False, null=True),
        ),
    ]
