# Generated by Django 3.2.5 on 2022-08-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0009_auto_20220809_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player_1_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='player_2_locked',
            field=models.BooleanField(default=True),
        ),
    ]
