# Generated by Django 3.2.5 on 2022-08-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0011_auto_20220810_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='player_1_locked',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player_2_locked',
        ),
        migrations.AlterField(
            model_name='game',
            name='player_1_uid',
            field=models.CharField(blank=True, default='p-e7b4c5ac-6ead-4269-9529-163846d0d750', editable=False, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_2_uid',
            field=models.CharField(blank=True, default='p-6515bd70-76b4-40e2-8340-f3c6f911993e', editable=False, max_length=25, null=True),
        ),
    ]
