# Generated by Django 3.2.5 on 2022-08-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0012_auto_20220810_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='winning_cell',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_1_uid',
            field=models.CharField(blank=True, default='p-50cc02dd-164a-4de4-a1a8-fb9b6279c17d', editable=False, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_2_uid',
            field=models.CharField(blank=True, default='s-3b941b21-f321-4779-a0bd-3b564479b854', editable=False, max_length=25, null=True),
        ),
    ]
