# Generated by Django 3.2.5 on 2022-08-10 11:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0013_auto_20220810_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player_1_uid',
            field=models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_2_uid',
            field=models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=25, null=True),
        ),
    ]
